1. Fill "Therapy History"
--> Push
2. Add GUI
--> Push
3. Match the code with visualization code
--> Push
4. About this project: (about - name - date - ...)
5. Write comments and manual for projects
--> Push
6. Find Relationship Examples for PDF
--> Send it in the group

In [166]:
import pandas as pd
import numpy as np
from scipy import stats

In [167]:
df = pd.read_csv("social_anxiety_dataset.csv")

In [168]:
df.head()

,Age,Gender,Occupation,Sleep Hours,Physical Activity (hrs/week),Caffeine Intake (mg/day),Alcohol Consumption (drinks/week),Smoking,Family History of Anxiety,Stress Level (1-10),...,Sweating Level (1-5),Dizziness,Medication,Therapy Sessions (per month),Recent Major Life Event,Diet Quality (1-10),Anxiety Level (1-10),Target,is_Anxious,Therapy History
0,59.0,Other,Teacher,7.0,2.4,40.0,5,Yes,No,4,...,5,No,No,0,Yes,1.0,2,0,0,Group Therapy
1,46.0,Female,Student,5.1,5.4,156.0,11,NaN,No,3,...,4,Yes,No,2,No,1.0,4,0,0,NaN
2,40.0,Other,Lawyer,5.1,1.9,570.0,14,Yes,Yes,9,...,3,No,No,6,Yes,4.0,9,1,1,NaN
3,40.0,Male,Nurse,7.6,0.9,129.0,0,No,No,9,...,2,No,NaN,2,No,2.0,6,0,0,NaN
4,26.0,Male,Other,6.7,3.0,64.0,13,No,No,15,...,4,No,Yes,0,Yes,4.0,3,0,0,NaN

In [169]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2030 entries, 0 to 2029
Data columns (total 22 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                1968 non-null   float64
 1   Gender                             1911 non-null   object
 2   Occupation                         2030 non-null   object
 3   Sleep Hours                        1994 non-null   float64
 4   Physical Activity (hrs/week)       2030 non-null   float64
 5   Caffeine Intake (mg/day)           1936 non-null   float64
 6   Alcohol Consumption (drinks/week)  2030 non-null   int64
 7   Smoking                            1924 non-null   object
 8   Family History of Anxiety          2030 non-null   object
 9   Stress Level (1-10)                2030 non-null   int64
 10  Heart Rate (bpm)                   2030 non-null   int64
 11  Breathing Rate (breaths/min)       2030 non-null   int64
 12  Sweating Level (1-5)               2030 non-null   int64
 13  Dizziness                          2030 non-null   object
 14  Medication                         1921 non-null   object
 15  Therapy Sessions (per month)       2030 non-null   int64
 16  Recent Major Life Event            2030 non-null   object
 17  Diet Quality (1-10)                1952 non-null   float64
 18  Anxiety Level (1-10)               2030 non-null   int64
 19  Target                             2030 non-null   int64
 20  is_Anxious                         2030 non-null   int64
 21  Therapy History                    203 non-null    object
dtypes: float64(5), int64(9), object(8)
memory usage: 349.0+ KB

In [170]:
df.describe()

,Age,Sleep Hours,Physical Activity (hrs/week),Caffeine Intake (mg/day),Alcohol Consumption (drinks/week),Stress Level (1-10),Heart Rate (bpm),Breathing Rate (breaths/min),Sweating Level (1-5),Therapy Sessions (per month),Diet Quality (1-10),Anxiety Level (1-10),Target,is_Anxious
count,1968.000000,1994.000000,2030.000000,1936.000000,2030.000000,2030.000000,2030.000000,2030.000000,2030.000000,2030.000000,1952.000000,2030.000000,2030.000000,2030.000000
mean,39.921748,6.424624,2.800246,306.275826,9.490148,6.028571,93.066502,20.955665,3.095567,2.359113,5.234119,3.922660,0.103448,0.103448
std,13.243754,2.161544,2.233899,208.012717,6.028653,3.137269,23.313430,5.182524,1.392697,2.148642,2.884946,2.139176,0.304619,0.304619
min,18.000000,-10.000000,-10.000000,0.000000,-10.000000,1.000000,60.000000,12.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000
25%,29.000000,5.800000,1.400000,177.750000,5.000000,3.000000,76.000000,17.000000,2.000000,1.000000,3.000000,2.000000,0.000000,0.000000
50%,40.000000,6.700000,2.800000,277.500000,10.000000,6.000000,93.000000,21.000000,3.000000,2.000000,5.000000,4.000000,0.000000,0.000000
75%,51.000000,7.500000,4.200000,391.000000,15.000000,9.000000,107.000000,26.000000,4.000000,3.000000,8.000000,5.000000,0.000000,0.000000
max,64.000000,11.000000,9.200000,1500.000000,19.000000,15.000000,220.000000,29.000000,5.000000,10.000000,10.000000,10.000000,1.000000,1.000000

In [171]:
categorical_columns = ["Gender", "Occupation", "Smoking", "Family History of Anxiety", "Dizziness", "Medication",
"Recent Major Life Event", "is_Anxious", "Therapy History"]

for column in categorical_columns:   
    print(df[column].value_counts(), "\n")

Gender
Female    657
Other     627
Male      627
Name: count, dtype: int64

Occupation
Student       182
Artist        172
Lawyer        167
Musician      163
Nurse         162
Doctor        161
Scientist     155
Teacher       151
Other         149
Athlete       147
Chef          146
Engineer      141
Freelancer    134
Name: count, dtype: int64

Smoking
Yes    1020
No      904
Name: count, dtype: int64

Family History of Anxiety
Yes    1058
No      972
Name: count, dtype: int64

Dizziness
Yes    1049
No      981
Name: count, dtype: int64

Medication
Yes    964
No     957
Name: count, dtype: int64

Recent Major Life Event
Yes    1040
No      990
Name: count, dtype: int64

is_Anxious
0    1820
1     210
Name: count, dtype: int64

Therapy History
No previous history                   60
Group Therapy                         54
Cognitive Behavioral Therapy (CBT)    45
Psychodynamic Therapy                 44
Name: count, dtype: int64

In [172]:
# Testing a sample for 1 column
table = pd.crosstab(df["Gender"], df["is_Anxious"])
table

is_Anxious    0   1
Gender
Female      596  61
Male        556  71
Other       561  66

In [173]:
percentages = table.apply(lambda x: x / x.sum() * 100, axis=1)
percentages

is_Anxious          0          1
Gender
Female      90.715373   9.284627
Male        88.676236  11.323764
Other       89.473684  10.526316

In [174]:
chi2, p, dof, expected = stats.chi2_contingency(table)

print("Chi-square:", chi2)
print("p-value:", p)
print("Degrees of freedom:", dof)

Chi-square: 1.4637842459690373
p-value: 0.4809980211180541
Degrees of freedom: 2

In [175]:
n = table.to_numpy().sum()
cramers_v = np.sqrt(chi2 / (n * min(table.shape[0] - 1, table.shape[1] - 1)))

print("Cramer's V:", cramers_v)

Cramer's V: 0.027676310279555586

In [176]:
# a function for 1 column

def categorical_relationship_one_column(df, col1, col2, alpha=0.05):
    print(f"Analyzing relationship between [{col1}] and [{col2}]\n")
    
    print("Statistical hypotheses:")
    print(f"H0: Variables '{col1}' and '{col2}' are completely independent (no relationship).")
    print(f"H1: Variables '{col1}' and '{col2}' are dependent.\n")
    
    contingency_table = pd.crosstab(df[col1], df[col2])
    
    chi2, p_value, dof, expected = stats.chi2_contingency(contingency_table)
    
    n = contingency_table.to_numpy().sum()
    min_dim = min(contingency_table.shape[0] - 1, contingency_table.shape[1] - 1)
    cramers_v = np.sqrt(chi2 / (n * min_dim))
    
    print("Test results:")
    print(f"Chi-square value: {chi2:.4f}")
    print(f"P-value: {p_value:.8f}")
    print(f"Degrees of freedom (DoF): {dof}")
    print(f"Cramer's V (strength of association): {cramers_v:.4f} (0 - 1)\n")
    
    print("Conclusion:")
    if p_value < alpha:
        print(f"✅ H0 is rejected (P-value < {alpha}).")
        print(f"Result: There is sufficient statistical evidence to show a significant relationship between '{col1}' and '{col2}'.")
    else:
        print(f"❌ H0 is not rejected (P-value >= {alpha}).")
        print(f"Result: '{col1}' and '{col2}' appear to be independent.")

In [177]:
categorical_relationship_one_column(df, 'Gender', 'Occupation')

Analyzing relationship between [Gender] and [Occupation]

Statistical hypotheses:
H0: Variables 'Gender' and 'Occupation' are completely independent (no relationship).
H1: Variables 'Gender' and 'Occupation' are dependent.

Test results:
Chi-square value: 17.8506
P-value: 0.81019491
Degrees of freedom (DoF): 24
Cramer's V (strength of association): 0.0683 (0 - 1)

Conclusion:
❌ H0 is not rejected (P-value >= 0.05).
Result: 'Gender' and 'Occupation' appear to be independent.

In [178]:
# a function for 2 columns

def categorical_relationship_two_columns(df, col1, val1, col2, val2, target_col, alpha=0.05):
    segments = f"'{val1} {col1}' & '{val2} {col2}'"
    print(f"Analyzing [{segments}] vs [{target_col}]")
    
    condition = (df[col1] == val1) & (df[col2] == val2)
    
    temp_groups = np.where(condition, "Target Group", "Others")
    
    contingency_table = pd.crosstab(temp_groups, df[target_col])
    print("Contingency Table:")
    print(contingency_table, "\n")

    chi2, p_value, dof, expected = stats.chi2_contingency(contingency_table)
    
    n = contingency_table.to_numpy().sum()
    min_dim = min(contingency_table.shape[0] - 1, contingency_table.shape[1] - 1)
    cramers_v = np.sqrt(chi2 / (n * min_dim))
    
    print("Test results:")
    print(f"Chi-square value: {chi2:.4f}")
    print(f"P-value: {p_value:.8f}")
    print(f"Degrees of freedom (DoF): {dof}")
    print(f"Cramer's V: {cramers_v:.4f} (0 - 1)\n")
    
    print("Conclusion:")
    if p_value < alpha:
        print(f"✅ H0 is rejected (P-value < {alpha}).")
        print(f"Result: Significant relationship between [{segments}] and ['{target_col}'].")
    else:
        print(f"❌ H0 is not rejected (P-value >= {alpha}).")
        print(f"Result: No significant relationship between [{segments}] and ['{target_col}'].")

In [179]:
categorical_relationship_two_columns(df, 'Medication', 'Yes', 'Recent Major Life Event', 'Yes', 'is_Anxious')

Analyzing ['Yes Medication' & 'Yes Recent Major Life Event'] vs [is_Anxious]
Contingency Table:
is_Anxious       0    1
row_0
Others        1403  133
Target Group   417   77

Test results:
Chi-square value: 18.6050
P-value: 0.00001608
Degrees of freedom (DoF): 1
Cramer's V: 0.0957 (0 - 1)

Conclusion:
✅ H0 is rejected (P-value < 0.05).
Result: Significant relationship between ['Yes Medication' & 'Yes Recent Major Life Event'] and ['is_Anxious'].