1. Fill "Therapy History"
--> Push
2. Add GUI
--> Push
3. Match the code with visualization code
--> Push
4. About this project: (about - name - date - ...)
5. Write comments and manual for projects
--> Push
6. Find Relationship Examples for PDF
--> Send it in the group

In [1]:
import pandas as pd
import numpy as np
from scipy import stats

In [2]:
df = pd.read_csv("social_anxiety_dataset_cleaned.csv")

In [3]:
df.head()

,Unnamed: 0,Age,Gender,Occupation,Sleep Hours,Physical Activity (hrs/week),Caffeine Intake (mg/day),Alcohol Consumption (drinks/week),Smoking,Family History of Anxiety,...,Stress Band,Sweating Band,Diet Category,Anxiety Severity,Occupation Sector,Somatic Arousal Score,Recovery Capacity,Stress-Recovery Balance,Sleep-Caffeine Cycle,Inherited Risk Triggered
0,0,59.0,Other,Teacher,7.0,2.4,40.0,5.0,Yes,No,...,Moderate,High,Poor,Minimal,Professional,2,1,Coasting,0,0
1,1,46.0,Female,Student,5.1,5.4,156.0,11.0,Unknown,No,...,Low,High,Poor,Mild,Student,2,1,Coasting,0,0
2,2,40.0,Other,Lawyer,5.1,1.9,570.0,14.0,Yes,Yes,...,Severe,Moderate,Fair,Severe,Professional,2,0,Overloaded,1,1
3,3,40.0,Male,Nurse,7.6,0.9,129.0,0.0,No,No,...,Severe,Low,Poor,Moderate,Healthcare,1,1,Overloaded,0,0
4,4,26.0,Male,Other,6.7,3.0,64.0,13.0,No,No,...,Severe,High,Fair,Mild,Other,2,1,Overloaded,0,0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2030 entries, 0 to 2029
Data columns (total 46 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Unnamed: 0                                 2030 non-null   int64
 1   Age                                        2030 non-null   float64
 2   Gender                                     2030 non-null   object
 3   Occupation                                 2030 non-null   object
 4   Sleep Hours                                2030 non-null   float64
 5   Physical Activity (hrs/week)               2030 non-null   float64
 6   Caffeine Intake (mg/day)                   2030 non-null   float64
 7   Alcohol Consumption (drinks/week)          2030 non-null   float64
 8   Smoking                                    2030 non-null   object
 9   Family History of Anxiety                  2030 non-null   object
 10  Stress Level (1-10)                        2030 non-null   int64
 11  Heart Rate (bpm)                           2030 non-null   float64
 12  Breathing Rate (breaths/min)               2030 non-null   int64
 13  Sweating Level (1-5)                       2030 non-null   int64
 14  Dizziness                                  2030 non-null   object
 15  Medication                                 2030 non-null   object
 16  Therapy Sessions (per month)               2030 non-null   int64
 17  Recent Major Life Event                    2030 non-null   object
 18  Diet Quality (1-10)                        2030 non-null   int64
 19  Anxiety Level (1-10)                       2030 non-null   int64
 20  Target                                     2030 non-null   int64
 21  Therapy History                            2030 non-null   object
 22  Sleep Hours Outlier Flag                   2030 non-null   int64
 23  Physical Activity (hrs/week) Outlier Flag  2030 non-null   int64
 24  Caffeine Intake (mg/day) Outlier Flag      2030 non-null   int64
 25  High Stress Flag                           2030 non-null   int64
 26  Heart Rate (bpm) Outlier Flag              2030 non-null   int64
 27  Therapy Sessions (per month) Outlier Flag  2030 non-null   int64
 28  Age Group                                  2030 non-null   object
 29  Sleep Category                             2030 non-null   object
 30  Activity Level                             2030 non-null   object
 31  Caffeine Level                             2030 non-null   object
 32  Drinking Level                             1935 non-null   object
 33  Heart Rate Category                        2030 non-null   object
 34  Breathing Category                         2030 non-null   object
 35  Therapy Engagement                         1613 non-null   object
 36  Stress Band                                2030 non-null   object
 37  Sweating Band                              2030 non-null   object
 38  Diet Category                              2030 non-null   object
 39  Anxiety Severity                           2030 non-null   object
 40  Occupation Sector                          2030 non-null   object
 41  Somatic Arousal Score                      2030 non-null   int64
 42  Recovery Capacity                          2030 non-null   int64
 43  Stress-Recovery Balance                    2030 non-null   object
 44  Sleep-Caffeine Cycle                       2030 non-null   int64
 45  Inherited Risk Triggered                   2030 non-null   int64
dtypes: float64(6), int64(18), object(22)
memory usage: 729.7+ KB

In [5]:
df.describe()

,Unnamed: 0,Age,Sleep Hours,Physical Activity (hrs/week),Caffeine Intake (mg/day),Alcohol Consumption (drinks/week),Stress Level (1-10),Heart Rate (bpm),Breathing Rate (breaths/min),Sweating Level (1-5),...,Sleep Hours Outlier Flag,Physical Activity (hrs/week) Outlier Flag,Caffeine Intake (mg/day) Outlier Flag,High Stress Flag,Heart Rate (bpm) Outlier Flag,Therapy Sessions (per month) Outlier Flag,Somatic Arousal Score,Recovery Capacity,Sleep-Caffeine Cycle,Inherited Risk Triggered
count,2030.000000,2030.000000,2030.000000,2030.000000,2030.000000,2030.000000,2030.000000,2030.000000,2030.000000,2030.000000,...,2030.000000,2030.000000,2030.000000,2030.000000,2030.000000,2030.000000,2030.000000,2030.000000,2030.00000,2030.000000
mean,1014.500000,39.921748,6.672644,2.975165,294.238881,9.786432,5.954680,92.083744,20.955665,3.095567,...,0.014286,0.004926,0.014778,0.014778,0.014778,0.058621,1.919212,1.311330,0.37734,0.264532
std,586.154843,13.039840,1.183219,1.776260,148.919157,5.629003,2.979959,18.929407,5.182524,1.392697,...,0.118695,0.070030,0.120694,0.120694,0.120694,0.234971,1.020913,0.892783,0.48484,0.441192
min,0.000000,18.000000,3.750000,0.000000,0.000000,0.000000,1.000000,60.000000,12.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
25%,507.250000,29.000000,6.000000,1.600000,183.000000,5.000000,3.000000,76.000000,17.000000,2.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.00000,0.000000
50%,1014.500000,39.921748,6.700000,2.850000,284.000000,10.000000,6.000000,93.000000,21.000000,3.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,1.000000,0.00000,0.000000
75%,1521.750000,50.000000,7.500000,4.200000,384.000000,15.000000,9.000000,107.000000,26.000000,4.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,2.000000,1.00000,1.000000
max,2029.000000,64.000000,9.750000,8.100000,685.500000,19.000000,10.000000,153.500000,29.000000,5.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,4.000000,3.000000,1.00000,1.000000

In [6]:
categorical_columns = ["Gender", "Occupation", "Smoking", "Family History of Anxiety", "Stress Level (1-10)", "Sweating Level (1-5)", "Dizziness", "Medication",
"Recent Major Life Event", "Diet Quality (1-10)", "Anxiety Level (1-10)", "Target", "Therapy History"]

for column in categorical_columns:   
    print(df[column].value_counts(), "\n")

Gender
Female     657
Other      627
Male       627
Unknown    119
Name: count, dtype: int64

Occupation
Student       182
Artist        172
Lawyer        167
Musician      163
Nurse         162
Doctor        161
Scientist     155
Teacher       151
Other         149
Athlete       147
Chef          146
Engineer      141
Freelancer    134
Name: count, dtype: int64

Smoking
Yes        1020
No          904
Unknown     106
Name: count, dtype: int64

Family History of Anxiety
Yes    1058
No      972
Name: count, dtype: int64

Stress Level (1-10)
10    294
9     249
8     245
1     185
6     181
3     180
7     177
2     177
5     175
4     167
Name: count, dtype: int64

Sweating Level (1-5)
4    436
3    434
5    426
2    374
1    360
Name: count, dtype: int64

Dizziness
Yes    1049
No      981
Name: count, dtype: int64

Medication
Yes        964
No         957
Unknown    109
Name: count, dtype: int64

Recent Major Life Event
Yes    1040
No      990
Name: count, dtype: int64

Diet Quality (1-10)
3     302
2     223
1     221
4     210
6     190
8     185
7     179
9     175
10    173
5     172
Name: count, dtype: int64

Anxiety Level (1-10)
3     430
4     424
2     329
5     303
1     206
6     128
8      68
10     60
9      56
7      26
Name: count, dtype: int64

Target
0    1820
1     210
Name: count, dtype: int64

Therapy History
Unavailable    1455
Nothing         372
Available       203
Name: count, dtype: int64

In [7]:
# Testing a sample for 1 column
table = pd.crosstab(df["Gender"], df["Target"])
table

Target     0   1
Gender
Female   596  61
Male     556  71
Other    561  66
Unknown  107  12

In [8]:
percentages = table.apply(lambda x: x / x.sum() * 100, axis=1)
percentages

Target           0          1
Gender
Female   90.715373   9.284627
Male     88.676236  11.323764
Other    89.473684  10.526316
Unknown  89.915966  10.084034

In [9]:
chi2, p, dof, expected = stats.chi2_contingency(table)

print("Chi-square:", chi2)
print("p-value:", p)
print("Degrees of freedom:", dof)

Chi-square: 1.4750865980773975
p-value: 0.6880321511587402
Degrees of freedom: 3

In [10]:
n = table.to_numpy().sum()
cramers_v = np.sqrt(chi2 / (n * min(table.shape[0] - 1, table.shape[1] - 1)))

print("Cramer's V:", cramers_v)

Cramer's V: 0.026956328466115377

In [11]:
# a function for 1 column

def categorical_relationship_one_column(df, col1, col2, alpha=0.05):
    print(f"Analyzing relationship between [{col1}] and [{col2}]\n")
    
    print("Statistical hypotheses:")
    print(f"H0: Variables '{col1}' and '{col2}' are completely independent (no relationship).")
    print(f"H1: Variables '{col1}' and '{col2}' are dependent.\n")
    
    contingency_table = pd.crosstab(df[col1], df[col2])
    
    chi2, p_value, dof, expected = stats.chi2_contingency(contingency_table)
    
    n = contingency_table.to_numpy().sum()
    min_dim = min(contingency_table.shape[0] - 1, contingency_table.shape[1] - 1)
    cramers_v = np.sqrt(chi2 / (n * min_dim))
    
    print("Test results:")
    print(f"Chi-square value: {chi2:.4f}")
    print(f"P-value: {p_value:.8f}")
    print(f"Degrees of freedom (DoF): {dof}")
    print(f"Cramer's V (strength of association): {cramers_v:.4f} (0 - 1)\n")
    
    print("Conclusion:")
    if p_value < alpha:
        print(f"H0 is rejected (P-value < {alpha}).")
        print(f"Result: There is sufficient statistical evidence to show a significant relationship between '{col1}' and '{col2}'.")
    else:
        print(f"H0 is not rejected (P-value >= {alpha}).")
        print(f"Result: '{col1}' and '{col2}' appear to be independent.")

In [12]:
categorical_relationship_one_column(df, 'Inherited Risk Triggered', 'Target')

Analyzing relationship between [Inherited Risk Triggered] and [Target]

Statistical hypotheses:
H0: Variables 'Inherited Risk Triggered' and 'Target' are completely independent (no relationship).
H1: Variables 'Inherited Risk Triggered' and 'Target' are dependent.

Test results:
Chi-square value: 98.1108
P-value: 0.00000000
Degrees of freedom (DoF): 1
Cramer's V (strength of association): 0.2198 (0 - 1)

Conclusion:
H0 is rejected (P-value < 0.05).
Result: There is sufficient statistical evidence to show a significant relationship between 'Inherited Risk Triggered' and 'Target'.

In [13]:
# a function for 2 columns

def categorical_relationship_two_columns(df, col1, val1, col2, val2, target_col, alpha=0.05):
    segments = f"'{val1} {col1}' & '{val2} {col2}'"
    print(f"Analyzing [{segments}] vs [{target_col}]")
    
    condition = (df[col1] == val1) & (df[col2] == val2)
    
    temp_groups = np.where(condition, "Target Group", "Others")
    
    contingency_table = pd.crosstab(temp_groups, df[target_col])
    print("Contingency Table:")
    print(contingency_table, "\n")

    chi2, p_value, dof, expected = stats.chi2_contingency(contingency_table)
    
    n = contingency_table.to_numpy().sum()
    min_dim = min(contingency_table.shape[0] - 1, contingency_table.shape[1] - 1)
    cramers_v = np.sqrt(chi2 / (n * min_dim))
    
    print("Test results:")
    print(f"Chi-square value: {chi2:.4f}")
    print(f"P-value: {p_value:.8f}")
    print(f"Degrees of freedom (DoF): {dof}")
    print(f"Cramer's V: {cramers_v:.4f} (0 - 1)\n")
    
    print("Conclusion:")
    if p_value < alpha:
        print(f"H0 is rejected (P-value < {alpha}).")
        print(f"Result: Significant relationship between [{segments}] and ['{target_col}'].")
    else:
        print(f"H0 is not rejected (P-value >= {alpha}).")
        print(f"Result: No significant relationship between [{segments}] and ['{target_col}'].")

In [14]:
categorical_relationship_two_columns(df, 'Family History of Anxiety', 'Yes', 'Family History of Anxiety', 'Yes', 'Target')

Analyzing ['Yes Family History of Anxiety' & 'Yes Family History of Anxiety'] vs [Target]
Contingency Table:
Target          0    1
row_0
Others        936   36
Target Group  884  174

Test results:
Chi-square value: 87.3187
P-value: 0.00000000
Degrees of freedom (DoF): 1
Cramer's V: 0.2074 (0 - 1)

Conclusion:
H0 is rejected (P-value < 0.05).
Result: Significant relationship between ['Yes Family History of Anxiety' & 'Yes Family History of Anxiety'] and ['Target'].

In [44]:
def anova(df, c_col, n_col, alpha=0.05):
    print(f"Analyzing Variance (ANOVA) between [{c_col}] and [{n_col}]\n")
    
    print("Statistical hypotheses:")
    print(f"H0: The mean of '{n_col}' is the same across all groups of '{c_col}'.")
    print(f"H1: The mean of '{n_col}' is different for at least one group of '{c_col}'.\n")
    
    temp_df = df[[c_col, n_col]]

    groups = []

    for name, group in temp_df.groupby(c_col):

        group_values = group[n_col].values
        groups.append(group_values)

    f_stat, p_value = stats.f_oneway(*groups)

    print("Test results:")
    print(f"F-statistic: {f_stat:.4f}")
    print(f"P-value: {p_value:.8f}\n")

    print("Conclusion:")
    if p_value < alpha:
        print(f"H0 is rejected (P-value < {alpha}).")
        print(f"Result: There is a statistically significant difference in the mean of '{n_col}' across different '{c_col}' groups.")
    else:
        print(f"H0 is not rejected (P-value >= {alpha}).")
        print(f"Result: There is NO significant difference in the mean of '{n_col}' across the groups.")

In [54]:
anova(df, 'Gender', 'Breathing Rate (breaths/min)')

Analyzing Variance (ANOVA) between [Gender] and [Breathing Rate (breaths/min)]

Statistical hypotheses:
H0: The mean of 'Breathing Rate (breaths/min)' is the same across all groups of 'Gender'.
H1: The mean of 'Breathing Rate (breaths/min)' is different for at least one group of 'Gender'.

Test results:
F-statistic: 1.0891
P-value: 0.35246970

Conclusion:
H0 is not rejected (P-value >= 0.05).
Result: There is NO significant difference in the mean of 'Breathing Rate (breaths/min)' across the groups.